defaults:
  - _self_
  - task: pendulum_image

name: train_noisy_bc_transformer_real_image
_target_: diffusion_policy.workspace.train_bc_transformer_image_workspace.TrainBCTransformerImageWorkspace

shape_meta: ${task.shape_meta}
action_dim: ${task.action_dim}
task_name: ${task.name}
exp_name: "default"

n_obs_steps: 1
horizon: 8
n_action_steps: 1
n_latency_steps: 0
n_clean_obs_steps: 0
max_noise_level: 1.0
add_noise_during_inference: True
max_inference_noise_level: 0.2

dataset_obs_steps: null

n_emb: 256

past_action_visible: False
keypoint_visible_rate: 1.0
obs_as_cond: True
pred_action_steps_only: False
add_noise_to_lowdim_obs: False

policy:
  _target_: diffusion_policy.policy.noisy_bc_transformer_image_policy.NoisyBCTransformerImagePolicy

  model_partial:
    _target_: diffusion_policy.model.history_conditioned.bc_transformer.BCTransformer
    _partial_: True
    history_length: ${horizon}
    action_horizon: ${n_action_steps}

    n_layer: 8
    n_head: 4
    n_emb: ${n_emb}
    p_drop_emb: 0.0
    p_drop_attn: 0.2

    causal_attn: True

  action_head:
    _target_: diffusion_policy.model.history_conditioned.action_heads.Linear
    in_dim: ${n_emb}
    ac_dim: ${action_dim}
  # action_head:
  #   _target_: diffusion_policy.model.history_conditioned.action_heads.GaussianMixture
  #   num_modes: 5
  #   in_dim: ${n_emb}
  #   ac_dim: ${action_dim}
  
  shape_meta: ${shape_meta}
  history_length: ${horizon}
  action_dim: ${action_dim}
  n_action_steps: ${n_action_steps}

  # Obs encoder
  crop_shape: [216, 288]
  obs_encoder_group_norm: True
  eval_fixed_crop: True

  # scheduler.step params
  # predict_epsilon: True

  n_clean_obs_steps: ${n_clean_obs_steps}
  max_noise_level: ${max_noise_level}
  add_noise_during_inference: ${add_noise_during_inference}
  max_inference_noise_level: ${max_inference_noise_level}
  add_noise_to_lowdim_obs: ${add_noise_to_lowdim_obs}

ema:
  _target_: diffusion_policy.model.diffusion.ema_model.EMAModel
  update_after_step: 0
  inv_gamma: 1.0
  power: 0.75
  min_value: 0.0
  max_value: 0.9999

dataloader:
  batch_size: 24
  num_workers: 5
  shuffle: True
  pin_memory: True
  persistent_workers: True

val_dataloader:
  batch_size: 24
  num_workers: 5
  shuffle: False
  pin_memory: True
  persistent_workers: True

optimizer:
  learning_rate: 1.0e-4
  transformer_weight_decay: 1.0e-3
  obs_encoder_weight_decay: 1.0e-6
  betas: [0.9, 0.95]

inference_sweep:
  perform_inference_sweep: False

training:
  device: "cuda:0"
  seed: 42
  debug: False
  resume: True
  # optimization
  lr_scheduler: cosine
  # Transformer needs LR warmup
  lr_warmup_steps: 1000
  num_epochs: 500
  gradient_accumulate_every: 1
  use_ema: True
  # training loop control
  # in epochs
  rollout_every: 25
  checkpoint_every: 25
  val_every: 25
  sample_every: 25
  # steps per epoch
  max_train_steps: null
  max_val_steps: null
  # misc
  tqdm_interval_sec: 1.0

logging:
  project: diffusion_policy_debug
  resume: True
  mode: online
  name: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}
  tags: ["${name}", "${task_name}", "${exp_name}"]
  id: null
  group: null

checkpoint:
  topk:
    monitor_key: train_loss
    mode: min
    k: 2
    format_str: 'epoch={epoch:04d}-train_loss={train_loss:.3f}.ckpt'
  save_last_ckpt: True
  save_last_snapshot: False

multi_run:
  run_dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  wandb_name_base: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  sweep:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
    subdir: ${hydra.job.num}
